/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compiler;

/**
 *
 * @author Baron
 */

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

public class canvas extends javax.swing.JFrame {

    /**
     * Creates new form canvas
     */
    Graphics g;
    int regexNo = 0;
    
    public canvas() {
        initComponents();
    }
    
    public canvas(String data, int regex) {
        initComponents();
        g = drawingBoard.getGraphics();     
        drawingBoard.paintComponents(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setStroke(new BasicStroke(3));
        sampleRead.setText(data);
        if(regex == 1){
            dfaDisplay.setEnabled(true);
            regexNo = 1;
        } else if (regex == 2){
            dfaDisplay.setEnabled(false);
            regexNo = 2;
        }
        this.setTitle("SIMULATION");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        drawingBoard = new javax.swing.JPanel();
        dfaDisplay = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        sampleRead = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        drawingBoard.setBackground(new java.awt.Color(255, 255, 255));

        dfaDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regex1-2-3.png"))); // NOI18N
        dfaDisplay.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/regex2-2.png"))); // NOI18N

        javax.swing.GroupLayout drawingBoardLayout = new javax.swing.GroupLayout(drawingBoard);
        drawingBoard.setLayout(drawingBoardLayout);
        drawingBoardLayout.setHorizontalGroup(
            drawingBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawingBoardLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(dfaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        drawingBoardLayout.setVerticalGroup(
            drawingBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawingBoardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dfaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        sampleRead.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sampleRead.setForeground(new java.awt.Color(255, 255, 255));
        sampleRead.setText(" ");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(sampleRead, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sampleRead)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drawingBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(drawingBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void blink(String state, int iterations) throws InterruptedException{
        switch(state){
            case "a1":
                if(iterations == 1){
                    g.setColor(Color.green);        // A-1-DFA1
                    g.drawOval(86, 296, 33, 69);    // A-1-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(86, 296, 33, 69);
                }
                
                break;
            case "b1":
                if(iterations == 1){
                    g.setColor(Color.green);        // B-1-DFA1
                    g.drawOval(86, 70, 33, 70);     // B-1-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-1-DFA1
                    g.drawOval(86, 70, 33, 70);
                }
                
                break;
            case "a2":
                if(iterations == 1){
                    g.setColor(Color.green);        // A-2-DFA1
                    g.drawOval(160, 70, 33, 69);    // A-2-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // A-2-DFA1
                    g.drawOval(160, 70, 33, 69);
                }
                
                break;
            case "b2":
                if(iterations == 1){
                    g.setColor(Color.green);        // B-2-DFA1
                    g.drawOval(160, 295, 33, 69);   // B-2-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-2-DFA1
                    g.drawOval(160, 295, 33, 69);   // B-2-DFA1
                }
                
                break;
            case "t1":
                if(iterations == 1){
                    g.setColor(Color.green);        // T-DFA1
                    g.drawOval(122, 182, 33, 69);
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // T-DFA1
                    g.drawOval(122, 182, 33, 69);
                } else if(iterations == 9){
                    g.setColor(Color.red);          // T-DFA1
                    g.drawOval(122, 182, 33, 69);
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // T-DFA1
                    g.drawOval(122, 182, 33, 69);
                }
                 
                break;
            case "a3":
                if(iterations == 1){
                    g.setColor(Color.green);        // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                } else if (iterations == 2){
                    g.setColor(Color.orange);       // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                } else if (iterations == 3){
                    g.setColor(Color.pink);         // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // A-3-DFA1
                    g.drawOval(222, 183, 33, 70);   // A-3-DFA1
                }
                
                break;
            case "b4":
                if(iterations == 1){
                    g.setColor(Color.green);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                } else if (iterations == 2){
                    g.setColor(Color.orange);       // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                } else if (iterations == 3){
                    g.setColor(Color.pink);         // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                } else if (iterations == 4){
                    g.setColor(Color.cyan);         // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                } else if (iterations == 5){
                    g.setColor(Color.magenta);         // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-4-DFA1
                    g.drawOval(325, 182, 34, 70);   // B-4-DFA1
                }
                
                break;
            case "a5":
                if(iterations == 1){
                    g.setColor(Color.green);        // A-5-DFA1
                    g.drawOval(428, 182, 34, 70);   // A-5-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // A-5-DFA1
                    g.drawOval(428, 182, 34, 70);   // A-5-DFA1
                }
                
                break;
            case "b5":
                if(iterations == 1){
                    g.setColor(Color.green);        // B-5-DFA1
                    g.drawOval(533, 182, 34, 70);   // B-5-DFA1    
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // B-5-DFA1
                    g.drawOval(533, 182, 34, 70);   // B-5-DFA1
                }
                
                break;
            case "ab6":
                if(iterations == 1){
                    g.setColor(Color.green);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                } else if(iterations == 2){
                    g.setColor(Color.orange);       // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                } else if(iterations == 3){
                    g.setColor(Color.pink);         // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                } else if(iterations == 4){
                    g.setColor(Color.cyan);         // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                } else if(iterations == 5){
                    g.setColor(Color.magenta);      // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // AB-6-DFA1
                    g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
                } 
                 
                break;
            case "start":
                if(iterations == 1){
                    g.setColor(Color.green);        // NULL-DFA1
                    g.drawOval(32, 183, 33, 69);    // NULL-DFA1
                    Thread.sleep(2000);
                    g.setColor(Color.black);        // NULL-DFA1
                    g.drawOval(32, 183, 33, 69);    // NULL-DFA1
                }
                
                break;
        }

    }
    
    private void blink1(String state, int iterations) throws InterruptedException{
        switch(state){
            //green, orange, pink, cyan, magenta
            case "start":
                if(iterations == 1){
                    g.setColor(Color.green);        // START-DFA2
                    g.drawOval(27, 217, 36, 53);    // START-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(27, 217, 36, 53);
                }
                
                break;
            case "101":
                if(iterations == 1){
                    g.setColor(Color.green);        // 10-1-DFA2
                    g.drawOval(111, 216, 37, 53);   // 10-1-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(111, 216, 37, 53);
                }
                
                break;
//            case "02":
//                if(iterations == 1){
//                    g.setColor(Color.green);         // 0-2-DFA2
//                    g.drawOval(214, 172, 37, 54);    // 0-2-DFA2
//                    Thread.sleep(2000);
//                    g.setColor(Color.black);
//                    g.drawOval(214, 172, 37, 54);
//                }
//                
//                break;
            case "02":
                if(iterations == 1){
                    g.setColor(Color.green);         // 0-3-DFA2
                    g.drawOval(329, 176, 37, 52);    // 0-3-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(329, 176, 37, 52);
                }
                
                break;
            case "14":
                if(iterations == 1){
                    g.setColor(Color.green);         // 1-4-DFA2
                    g.drawOval(476, 218, 37, 52);    // 1-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(476, 218, 37, 52);
                } else if(iterations == 2){
                    g.setColor(Color.orange);        // 1-4-DFA2
                    g.drawOval(476, 218, 37, 52);    // 1-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(476, 218, 37, 52);
                } else if(iterations == 3){
                    g.setColor(Color.pink);          // 1-4-DFA2
                    g.drawOval(476, 218, 37, 52);    // 1-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(476, 218, 37, 52);
                } else if(iterations == 4){
                    g.setColor(Color.cyan);          // 1-4-DFA2
                    g.drawOval(476, 218, 37, 52);    // 1-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(476, 218, 37, 52);
                } else if(iterations == 5){
                    g.setColor(Color.magenta);       // 1-4-DFA2
                    g.drawOval(476, 218, 37, 52);    // 1-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(476, 218, 37, 52);
                } 
                
                break;
            case "04":
                if(iterations == 1){
                    g.setColor(Color.green);        // 0-4-DFA2
                    g.drawOval(477, 93, 37, 53);    // 0-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(477, 93, 37, 53);
                } else if(iterations == 2){
                    g.setColor(Color.orange);       // 0-4-DFA2
                    g.drawOval(477, 93, 37, 53);    // 0-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(477, 93, 37, 53);
                } else if(iterations == 3){
                    g.setColor(Color.pink);         // 0-4-DFA2
                    g.drawOval(477, 93, 37, 53);    // 0-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(477, 93, 37, 53);
                } else if(iterations == 4){
                    g.setColor(Color.cyan);         // 0-4-DFA2
                    g.drawOval(477, 93, 37, 53);    // 0-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(477, 93, 37, 53);
                } else if(iterations == 5){
                    g.setColor(Color.magenta);      // 0-4-DFA2
                    g.drawOval(477, 93, 37, 53);    // 0-4-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(477, 93, 37, 53);
                } 
                
                break;
            case "05":
                if(iterations == 1){
                    g.setColor(Color.green);         // 0-5-DFA2
                    g.drawOval(614, 223, 37, 53);    // 0-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(614, 223, 37, 53);
                } else if(iterations == 2){
                    g.setColor(Color.orange);        // 0-5-DFA2
                    g.drawOval(614, 223, 37, 53);    // 0-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(614, 223, 37, 53);
                } else if(iterations == 3){
                    g.setColor(Color.pink);          // 0-5-DFA2
                    g.drawOval(614, 223, 37, 53);    // 0-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(614, 223, 37, 53);
                } else if(iterations == 4){
                    g.setColor(Color.cyan);          // 0-5-DFA2
                    g.drawOval(614, 223, 37, 53);    // 0-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(614, 223, 37, 53);
                } else if(iterations == 5){
                    g.setColor(Color.magenta);       // 0-5-DFA2
                    g.drawOval(614, 223, 37, 53);    // 0-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(614, 223, 37, 53);
                } 
                
                break;
            case "15":
                if(iterations == 1){
                    g.setColor(Color.green);         // 1-5-DFA2
                    g.drawOval(628, 331, 37, 52);    // 1-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(628, 331, 37, 52);
                } else if(iterations == 2){
                    g.setColor(Color.orange);        // 1-5-DFA2
                    g.drawOval(628, 331, 37, 52);    // 1-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(628, 331, 37, 52);
                } else if(iterations == 3){
                    g.setColor(Color.pink);          // 1-5-DFA2
                    g.drawOval(628, 331, 37, 52);    // 1-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(628, 331, 37, 52);
                } else if(iterations == 4){
                    g.setColor(Color.cyan);          // 1-5-DFA2
                    g.drawOval(628, 331, 37, 52);    // 1-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(628, 331, 37, 52);
                } else if(iterations == 5){
                    g.setColor(Color.magenta);       // 1-5-DFA2
                    g.drawOval(628, 331, 37, 52);    // 1-5-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(628, 331, 37, 52);
                } 
                
                break;
            case "106":
                if(iterations == 1){
                    g.setColor(Color.green);        // 10-6-DFA2
                    g.drawOval(650, 94, 37, 53);    // 10-6-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(650, 94, 37, 53);
                } else if(iterations == 2){
                    g.setColor(Color.orange);       // 10-6-DFA2
                    g.drawOval(650, 94, 37, 53);    // 10-6-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(650, 94, 37, 53);
                } else if(iterations == 3){
                    g.setColor(Color.pink);         // 10-6-DFA2
                    g.drawOval(650, 94, 37, 53);    // 10-6-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(650, 94, 37, 53);
                } else if(iterations == 4){
                    g.setColor(Color.cyan);         // 10-6-DFA2
                    g.drawOval(650, 94, 37, 53);    // 10-6-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(650, 94, 37, 53);
                } else if(iterations == 5){
                    g.setColor(Color.magenta);      // 10-6-DFA2
                    g.drawOval(650, 94, 37, 53);    // 10-6-DFA2
                    Thread.sleep(2000);
                    g.setColor(Color.black);
                    g.drawOval(650, 94, 37, 53);
                }
                
                break;
        }
    }
    
    private void algorithm(String sample) throws InterruptedException{
        //(aba+bab)(a+b)*(bab)(a+b)*(a+b+ab+ba)(a+b+aa)*
        // SAMPLE STRING : abababa
        System.out.println(sample);
        char end = 'n';
        for(int i = 0; i < sample.length(); i++){
            char input = sample.charAt(i);
            System.out.println(input +" "+i);    
            if(i < 3){
                if(input == 'a'){
                    if(i == 0){
                        blink("start", 1);
                        blink("a1", 1);
                    } else if (sample.charAt(0) == 'b' && i == 1){
                        blink("a2", 1);
                    } else if (sample.charAt(0) == 'a' && i == 1){
                        blink("t1", 9);
                        return;
                    } else if (sample.charAt(1) == 'a' && i == 2){
                        blink("t1", 9);
                        return;
                    } else if (sample.charAt(1) == 'b' && i == 2){
                        blink("a3", 1);
                    }
                } 
                else if(input == 'b'){
                    if(i == 0){
                        blink("start", 1);
                        blink("b1", 1);
                    } else if (sample.charAt(0) == 'b' && i == 1){
                        blink("t1", 9);
                        return;
                    } else if (sample.charAt(0) == 'a' && i == 1){
                        blink("b2", 1);
                    } else if (sample.charAt(1) == 'b' && i == 2){     
                        blink("t1", 9);
                        return;
                    } else if (sample.charAt(1) == 'a' && i == 2){
                        blink("a3", 1);
                    }
                }
            } else if (i < 6 && i >= 2){
                //ababbab
                //bababab
                if (input == 'a'){
                    if(i == 3){
                        blink("a3", 2);
                    } else if (sample.charAt(3) == 'b' && sample.charAt(5) == 'b' && i == 4){
                        blink("a5", 1);
                    } else if (sample.charAt(3) == 'b' && sample.charAt(5) == 'a' && i == 4){
                        blink("a3", 1);
                    } else if(sample.charAt(4) == 'a' && sample.charAt(3) == 'b' && i == 5){
                        blink("a3", 2);
                    } else if(sample.charAt(4) == 'b' && sample.charAt(3) == 'a' && i == 5){
                        blink("a5", 1);
                    } else if(sample.charAt(4) == 'b' && sample.charAt(3) == 'b' && i == 5){
                        blink("a5", 1);
                    } 
                } 
                else if (input == 'b'){
                    if(i == 3){
                        blink("b4", 1);
                    } else if (sample.charAt(3) == 'a' && i == 4){
                        blink("b4", 1);
                    } else if (sample.charAt(3) == 'b' && i == 4){
                        blink("b4", 2);
                    } else if(sample.charAt(3) == 'b' && sample.charAt(2) == 'b' && i == 4){
                        blink("b4", 3);
                    } else if (sample.charAt(4) == 'b' && sample.charAt(3) == 'b' && i == 5){
                        blink("b4", 4);
                    }else if (sample.charAt(4) == 'a' && sample.charAt(3) == 'b' && i == 5){
                        blink("b5", 1);
                        end = 'y';
                    } else if (sample.charAt(4) == 'a' && sample.charAt(3) == 'a' && i == 5){
                        blink("b4", 1);
                    } 
                }
            } else if (i < 9 && i >= 4){
                //babbaa
                //ababababa
                if(input == 'a'){
                    if(sample.charAt(5) == 'a' && sample.charAt(4) == 'a' && i == 6){
                        blink("a3", 3);
                    } else if (sample.charAt(5) == 'b' && sample.charAt(4) == 'b' && i == 6){
                        blink("a5", 1);
                    } else if (end == 'y' && i == 6){
                        blink("ab6", 1);
                    } else if (sample.charAt(5) == 'b' && sample.charAt(4) == 'a' && i == 6){
                        blink("a5", 1);
                    } else if (end == 'y' && i == 7){
                        blink("ab6", 2);
                    } else if (sample.charAt(6) == 'b' && sample.charAt(5) == 'a' && i == 7){
                        blink("a5", 1);
                    } else if(sample.charAt(6) == 'a' && sample.charAt(5) == 'a' && i == 7){
                        blink("a3", 3);
                    } else if (end == 'y' && i == 8){
                        blink("ab6", 3);
                    } else if (sample.charAt(7) == 'b' && sample.charAt(6) == 'a' && i == 8){
                        blink("a5", 1);
                    } 
                }
                else if(input == 'b')
                {
                    //abababba babababba
                    if (sample.charAt(5) == 'a' && sample.charAt(4) == 'b' && i == 6){
                        blink("b5", 1);
                        end = 'y';
                    } else if (end == 'y' && i == 6){
                        blink("ab6", 1);
                    } else if (sample.charAt(5) == 'a' && sample.charAt(4) == 'a' && i == 6){
                        blink("b4", 1);
                    } else if (sample.charAt(5) == 'b' && sample.charAt(4) == 'a' && i == 6){
                        blink("b4", 1);
                    } else if (end == 'y' && i == 7){
                        blink("ab6", 2);
                    } else if (end == 'y' && i == 7){
                        blink("ab6", 2);
                    } else if (sample.charAt(6) == 'a' && sample.charAt(5) == 'a' && i == 7){
                        blink("b4", 1);
                    } else if (end == 'y' && i == 8){
                        blink("ab6", 3);
                    } else if (end == 'y' && i == 8){
                        blink("ab6", 3);
                    } else if (sample.charAt(7) == 'a' && sample.charAt(6) == 'b' && i == 8){
                        blink("b5", 1);
                        end = 'y';
                    }
                }
                
            } else if (i < 15 && i >= 9) {
                //babaaba
                if (input == 'a')
                {
                    if(sample.charAt(8) == 'b' && sample.charAt(7) == 'a' && i == 9){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 9){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 10){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 11){
                        blink("ab6", 1);
                    }
                } 
                else if (input == 'b') 
                {
                    if(sample.charAt(8) == 'b' && sample.charAt(7) == 'a' && i == 9){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 9){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 10){
                        blink("ab6", 1);
                    } else if(end == 'y' && i == 11){
                        blink("ab6", 1);
                    }
                }
            }
        }
    }
    
    private void algorithm1(String sample) throws InterruptedException{
        
        System.out.println(sample);
        char end = 'n';
        int encounter106 = 0;
        if(encounter106 > 5){
            encounter106 = 0;
        }
        for(int i = 0; i < sample.length(); i++){
            char input = sample.charAt(i);
            System.out.println(input +" "+i);
            if(encounter106 == 5){
                encounter106 = 0;
            }
            if(i < 3){
                if(input == '0')
                {
                    if(i == 0){
                        blink1("start", 1);
                        blink1("101", 1);
                    } else if (i == 1){
                        blink1("02", 1);
                    }  else if (sample.charAt(1) == '1' && i == 2){
                        blink1("05", 1);
                    } else if (sample.charAt(1) == '0' && i == 2){
                        blink1("04", 1);
                    }
                }
                else if (input == '1')
                {
                    if(i == 0){
                        blink1("start", 1);
                        blink1("101", 1);
                    } else if (i == 1){
                        blink1("14", 1);
                    } else if (sample.charAt(1) == '1' && i == 2){
                        blink1("15", 1);
                    } else if (sample.charAt(1) == '0' && i == 2){
                        blink1("14", 1); 
                    }
                }
            }
            else if (i < 6){
                if(input == '0')
                {
                    if (end == 'y' && i == 3){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(1) == '0' && sample.charAt(2) == '0' && i == 3){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(1) == '1' && sample.charAt(2) == '0' && i == 3){
                        blink1("04", 1);
                    } else if (sample.charAt(1) == '1' && sample.charAt(2) == '1' && i == 3){
                        blink1("05", 1);
                    } else if (sample.charAt(1) == '0' && sample.charAt(2) == '1' && i == 3){
                        blink1("05", 1);
                    } else if (end == 'y' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '1' && i == 4){
                        blink1("05", 1);
                    } else if (sample.charAt(2) == '1' && sample.charAt(3) == '0' && i == 4){
                        blink1("04", 1);
                    } else if (sample.charAt(1) == '0' && sample.charAt(2) == '1' && sample.charAt(3) == '1' && i == 4){
                        blink1("05", 1);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '0' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (end == 'y' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(3) == '1' && sample.charAt(4) == '1' && i == 5){
                        blink1("05", 1);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '1' && sample.charAt(4) == '0' && i == 5){
                        blink1("04", 1);
                    } else if (sample.charAt(2) == '1' && sample.charAt(3) == '0' && sample.charAt(4) == '1' && i == 5){
                        blink1("04", 1);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '0' && sample.charAt(4) == '1' && i == 5){
                        blink1("05", 1);
                    } else if (sample.charAt(2) == '1' && sample.charAt(3) == '1' && sample.charAt(4) == '0' && i == 5){
                        blink1("04", 1);
                    } else if (sample.charAt(3) == '0' && sample.charAt(4) == '0' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    }
                }
                else if (input == '1')
                {
                    if (end == 'y' && i == 3){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(1) == '0' && sample.charAt(2) == '0' && i == 3){
                        blink1("14", 1);
                    } else if (sample.charAt(1) == '1' && sample.charAt(2) == '0' && i == 3){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(0) == '1' && sample.charAt(1) == '0' && sample.charAt(2) == '1' && i == 3){
                        blink1("15", 1);
                    } else if (sample.charAt(1) == '0' && sample.charAt(2) == '1' && i == 3){
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(1) == '1' && sample.charAt(2) == '1' && i == 3){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (end == 'y' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '1' && i == 4){
                        blink1("15", 1);
                    } else if (sample.charAt(2) == '1' && sample.charAt(3) == '1' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '0' && sample.charAt(1) == '1' && i == 4){
                        blink1("14", 1);
                    } else if (sample.charAt(2) == '0' && sample.charAt(3) == '0' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(2) == '1' && sample.charAt(3) == '0' && i == 4){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (end == 'y' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(4) == '0' && sample.charAt(3) == '0' && sample.charAt(2) == '0' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(4) == '0' && sample.charAt(3) == '0' && sample.charAt(2) == '1' && i == 5){
                        blink1("14", 1);
                    } else if (sample.charAt(4) == '1' && sample.charAt(3) == '0' && sample.charAt(2) == '0' && i == 5){
                        blink1("15", 1);
                    } else if (sample.charAt(4) == '1' && sample.charAt(3) == '0' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if (sample.charAt(4) == '0' && sample.charAt(3) == '1' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if (sample.charAt(4) == '1' && sample.charAt(3) == '1' && i == 5){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } 
                }
            }
            else if (i < 9) {
                if (input == '0') {
                    if(end == 'y' && i == 6){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '0' && i == 6){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(sample.charAt(5) == '1' && sample.charAt(4) == '0' && i == 6){
                        blink1("05", 1);
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '1' && sample.charAt(3) == '1' && i == 6){
                        blink1("04", 1);
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '1' && sample.charAt(3) == '0' && i == 6){
                        blink1("04", 1);
                    } else if(sample.charAt(5) == '1' && sample.charAt(4) == '1' && sample.charAt(3) == '0' && i == 6){
                        blink1("05", 1);
                    } else if(end == 'y' && i == 7){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(6) == '0' && sample.charAt(5) == '1' && i == 7){
                        blink1("04", 1);
                    } else if(sample.charAt(6) == '1' && sample.charAt(5) == '1' && sample.charAt(4) == '0' && i == 7){
                        blink1("05", 1);
                    } else if(sample.charAt(6) == '1' && sample.charAt(5) == '0' && sample.charAt(4) == '0' && i == 7){
                        blink1("05", 1);
                    } else if(sample.charAt(6) == '0' && sample.charAt(5) == '0' && sample.charAt(4) == '1' && i == 7){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(end == 'y' && i == 8){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(7) == '1' && sample.charAt(6) == '0' && sample.charAt(5) == '0' && i == 8){
                        blink1("05", 1);
                    }
                }
                else if  (input == '1') {
                    if(end == 'y' && i == 6){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '0' && i == 6){
                        blink1("14", 1); 
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '1' && sample.charAt(3) == '0' && i == 6){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(sample.charAt(5) == '0' && sample.charAt(4) == '1' && sample.charAt(3) == '1' && i == 6) {
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(sample.charAt(5) == '1' && sample.charAt(4) == '0' && sample.charAt(3) == '0' && i == 6) {
                        blink1("15", 1);
                    } else if(sample.charAt(5) == '1' && sample.charAt(4) == '1' && sample.charAt(3) == '0' && i == 6) {
                        blink1("15", 1);
                    } else if(end == 'y' && i == 7){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(6) == '0' && sample.charAt(5) == '0' && sample.charAt(4) == '1' && i == 7){
                        blink1("14", 1);
                    } else if(sample.charAt(6) == '1' && sample.charAt(5) == '0' && sample.charAt(4) == '0' && i == 7){
                        blink1("15", 1);
                    } else if(sample.charAt(6) == '0' && sample.charAt(5) == '1' && sample.charAt(4) == '1' && i == 7){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(sample.charAt(6) == '1' && sample.charAt(5) == '1' && sample.charAt(4) == '0' && i == 7){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(end == 'y' && i == 8){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(7) == '0' && sample.charAt(6) == '1' && sample.charAt(5) == '0' && i == 8){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(sample.charAt(7) == '1' && sample.charAt(6) == '0' && sample.charAt(5) == '0' && i == 8){
                        blink1("15", 1);
                    } else if(sample.charAt(7) == '1' && sample.charAt(6) == '1' && sample.charAt(5) == '0' && i == 8){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    }
                }
            }
            else if (i < 11)
            {
                if (input == '0'){
                    if(end == 'y' && i == 9){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(8) == '0' && sample.charAt(7) == '1' && sample.charAt(6) == '0' && i == 9){
                        blink1("04", 1);
                    } else if(sample.charAt(8) == '1' && sample.charAt(7) == '1' && sample.charAt(6) == '0' && i == 9){
                        blink1("05", 1);
                    } else if(end == 'y' && i == 10){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(9) == '0' && sample.charAt(8) == '0' && sample.charAt(7) == '1' && i == 10){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    }
                }
                else if (input == '1')
                {
                    if(end == 'y' && i == 9){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(8) == '0' && sample.charAt(7) == '1' && sample.charAt(6) == '0' && i == 9){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    } else if(end == 'y' && i == 10){
                        encounter106++;
                        blink1("106", encounter106);
                    } else if(sample.charAt(9) == '0' && sample.charAt(8) == '1' && sample.charAt(7) == '1' && i == 10){
                        encounter106++;
                        blink1("106", encounter106);
                        end = 'y';
                    }
                }
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
//        g.setColor(Color.green);        // NULL-DFA1
//        g.drawOval(32, 183, 33, 69);    // NULL-DFA1
//        
//        g.setColor(Color.green);        // B-1-DFA1
//        g.drawOval(86, 70, 33, 70);     // B-1-DFA1
//        
//        g.setColor(Color.green);        // A-1-DFA1
//        g.drawOval(86, 296, 33, 69);    // A-1-DFA1
//        
//        g.setColor(Color.green);        // B-2-DFA1
//        g.drawOval(160, 295, 33, 69);   // B-2-DFA1
//        
//        g.setColor(Color.green);        // A-2-DFA1
//        g.drawOval(160, 70, 33, 69);    // A-2-DFA1
//        
//        g.setColor(Color.green);        // T-DFA1
//        g.drawOval(122, 182, 33, 69);   // T-DFA1
//        
//        g.setColor(Color.green);        // A-3-DFA1
//        g.drawOval(222, 183, 33, 70);   // A-3-DFA1
//        
//        g.setColor(Color.green);        // B-4-DFA1
//        g.drawOval(325, 182, 34, 70);   // B-4-DFA1
//        
//        g.setColor(Color.green);        // A-5-DFA1
//        g.drawOval(428, 182, 34, 70);   // A-5-DFA1
//        
//        g.setColor(Color.green);        // B-5-DFA1
//        g.drawOval(533, 182, 34, 70);   // B-5-DFA1
//        
//        g.setColor(Color.green);        // AB-6-DFA1
//        g.drawOval(637, 183, 34, 70);   // AB-6-DFA1
            if(regexNo == 1){
                algorithm(sampleRead.getText());
            } else if(regexNo == 2){
                algorithm1(sampleRead.getText());
            }
        
        } catch (InterruptedException ex) {
            Logger.getLogger(canvas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(canvas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new canvas().setVisible(true);
            }
        });         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dfaDisplay;
    private javax.swing.JPanel drawingBoard;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel sampleRead;
    // End of variables declaration//GEN-END:variables
}
