/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compiler;


import java.awt.Graphics;
import javax.swing.JOptionPane;


/**
 *
 * @author Baron
 */
public class compileUI extends javax.swing.JFrame {

    /**
     * Creates new form compileUI
     */
    simulation sim = new simulation();
    
    public compileUI() {
        initComponents();
        this.setTitle("GROUP 6: AUTOMATA COMPILER");
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        simulateText = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        StringValidation = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sample1 = new javax.swing.JTextField();
        sample2 = new javax.swing.JTextField();
        sample3 = new javax.swing.JTextField();
        sample4 = new javax.swing.JTextField();
        sample5 = new javax.swing.JTextField();
        compileBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sample1Result = new javax.swing.JLabel();
        sample2Result = new javax.swing.JLabel();
        sample3Result = new javax.swing.JLabel();
        sample4Result = new javax.swing.JLabel();
        sample5Result = new javax.swing.JLabel();
        simulateSample1 = new javax.swing.JRadioButton();
        simulateSample2 = new javax.swing.JRadioButton();
        simulateSample3 = new javax.swing.JRadioButton();
        simulateSample4 = new javax.swing.JRadioButton();
        simulateSample5 = new javax.swing.JRadioButton();
        simulate1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        regEx = new javax.swing.JLabel();
        Regex1 = new javax.swing.JButton();
        Regex2 = new javax.swing.JButton();
        viewcfgpda = new javax.swing.JButton();
        DFA = new javax.swing.JLabel();
        dfapanel = new javax.swing.JPanel();
        dfa1 = new javax.swing.JLabel();
        dfa2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        StringValidation.setBackground(new java.awt.Color(255, 255, 255));
        StringValidation.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        StringValidation.setForeground(new java.awt.Color(255, 255, 255));
        StringValidation.setText("String Validation");
        StringValidation.setMaximumSize(new java.awt.Dimension(129, 21));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter String:");

        sample1.setBackground(new java.awt.Color(204, 204, 204));
        sample1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sample1KeyTyped(evt);
            }
        });

        sample2.setBackground(new java.awt.Color(204, 204, 204));
        sample2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sample2KeyTyped(evt);
            }
        });

        sample3.setBackground(new java.awt.Color(204, 204, 204));
        sample3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sample3KeyTyped(evt);
            }
        });

        sample4.setBackground(new java.awt.Color(204, 204, 204));
        sample4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sample4KeyTyped(evt);
            }
        });

        sample5.setBackground(new java.awt.Color(204, 204, 204));
        sample5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sample5KeyTyped(evt);
            }
        });

        compileBtn.setBackground(java.awt.SystemColor.activeCaptionText);
        compileBtn.setForeground(new java.awt.Color(255, 255, 255));
        compileBtn.setText("Compile");
        compileBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        compileBtn.setBorderPainted(false);
        compileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compileBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Results:");

        sample1Result.setBackground(new java.awt.Color(0, 153, 102));
        sample1Result.setForeground(new java.awt.Color(255, 255, 255));
        sample1Result.setText("------------");

        sample2Result.setForeground(new java.awt.Color(255, 255, 255));
        sample2Result.setText("------------");

        sample3Result.setForeground(new java.awt.Color(255, 255, 255));
        sample3Result.setText("------------");

        sample4Result.setForeground(new java.awt.Color(255, 255, 255));
        sample4Result.setText("------------");

        sample5Result.setForeground(new java.awt.Color(255, 255, 255));
        sample5Result.setText("------------");

        simulateText.add(simulateSample1);
        simulateSample1.setForeground(new java.awt.Color(255, 255, 255));
        simulateSample1.setSelected(true);
        simulateSample1.setText("Simulate");
        simulateSample1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateSample1ActionPerformed(evt);
            }
        });

        simulateText.add(simulateSample2);
        simulateSample2.setForeground(new java.awt.Color(255, 255, 255));
        simulateSample2.setText("Simulate");
        simulateSample2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateSample2ActionPerformed(evt);
            }
        });

        simulateText.add(simulateSample3);
        simulateSample3.setForeground(new java.awt.Color(255, 255, 255));
        simulateSample3.setText("Simulate");
        simulateSample3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateSample3ActionPerformed(evt);
            }
        });

        simulateText.add(simulateSample4);
        simulateSample4.setForeground(new java.awt.Color(255, 255, 255));
        simulateSample4.setText("Simulate");
        simulateSample4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateSample4ActionPerformed(evt);
            }
        });

        simulateText.add(simulateSample5);
        simulateSample5.setForeground(new java.awt.Color(255, 255, 255));
        simulateSample5.setText("Simulate");
        simulateSample5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateSample5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sample2Result, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sample3Result, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sample4Result, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sample5Result, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sample1Result, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simulateSample1)
                            .addComponent(simulateSample2)
                            .addComponent(simulateSample3)
                            .addComponent(simulateSample4)
                            .addComponent(simulateSample5))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample1Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulateSample1))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample2Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulateSample2))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample3Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulateSample3))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample4Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simulateSample4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sample5Result, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(simulateSample5))
                .addGap(62, 62, 62))
        );

        simulate1.setBackground(java.awt.SystemColor.activeCaptionText);
        simulate1.setForeground(new java.awt.Color(255, 255, 255));
        simulate1.setText("Simulate");
        simulate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        simulate1.setBorderPainted(false);
        simulate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sample5)
                    .addComponent(sample4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sample2)
                    .addComponent(sample3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(compileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(simulate1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sample1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sample1)
                .addGap(18, 18, 18)
                .addComponent(sample2)
                .addGap(18, 18, 18)
                .addComponent(sample3)
                .addGap(18, 18, 18)
                .addComponent(sample4)
                .addGap(18, 18, 18)
                .addComponent(sample5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulate1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Active Expression");
        jLabel4.setMaximumSize(new java.awt.Dimension(129, 21));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        regEx.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        regEx.setForeground(new java.awt.Color(255, 255, 255));
        regEx.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(regEx, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(regEx)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Regex1.setBackground(new java.awt.Color(102, 102, 102));
        Regex1.setForeground(new java.awt.Color(255, 255, 255));
        Regex1.setText("RegEx 1");
        Regex1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Regex1.setBorderPainted(false);
        Regex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regex1ActionPerformed(evt);
            }
        });

        Regex2.setBackground(new java.awt.Color(102, 102, 102));
        Regex2.setForeground(new java.awt.Color(255, 255, 255));
        Regex2.setText("RegEx 2");
        Regex2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Regex2.setBorderPainted(false);
        Regex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regex2ActionPerformed(evt);
            }
        });

        viewcfgpda.setBackground(new java.awt.Color(102, 102, 102));
        viewcfgpda.setForeground(new java.awt.Color(255, 255, 255));
        viewcfgpda.setText("View CFG + PDA");
        viewcfgpda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        viewcfgpda.setBorderPainted(false);
        viewcfgpda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcfgpdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Regex1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Regex2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewcfgpda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regex1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regex2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewcfgpda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        DFA.setBackground(new java.awt.Color(255, 255, 255));
        DFA.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        DFA.setForeground(new java.awt.Color(255, 255, 255));
        DFA.setText("DFA");
        DFA.setMaximumSize(new java.awt.Dimension(129, 21));

        dfapanel.setBackground(new java.awt.Color(153, 153, 153));
        dfapanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        dfa1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/dfa-1.png"))); // NOI18N

        dfa2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/regex2-2.png"))); // NOI18N

        javax.swing.GroupLayout dfapanelLayout = new javax.swing.GroupLayout(dfapanel);
        dfapanel.setLayout(dfapanelLayout);
        dfapanelLayout.setHorizontalGroup(
            dfapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dfapanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(dfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(dfapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dfapanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dfa2, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dfapanelLayout.setVerticalGroup(
            dfapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dfapanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dfa1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dfapanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dfapanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dfa2, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(StringValidation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dfapanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(StringValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DFA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(dfapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1391, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    compilerFunction comp[] = new compilerFunction[5];
    int count = 0;
    int regex = 0;
    
    private void Regex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regex2ActionPerformed
        // TODO add your handling code here:
        regEx.setText("((101+111+101)+(1+0+11))(1+0+01)*(111+000+101)(1+0)*");
        regex = 2;
        dfa1.setEnabled(true);
        dfa2.setEnabled(false);
    }//GEN-LAST:event_Regex2ActionPerformed

    private void Regex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regex1ActionPerformed
        // TODO add your handling code here:
        regEx.setText("(aba+bab)(a+b)*(bab)(a+b)*(a+b+ab+ba)(a+b+aa)*");
        regex = 1;
        dfa1.setEnabled(false);
        dfa2.setEnabled(true);
    }//GEN-LAST:event_Regex1ActionPerformed

    private void simulate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulate1ActionPerformed
        // TODO add your handling code here:
//        if(regex == 0){
//            JOptionPane.showMessageDialog(null, "No Regular Expression to Simulate!","Error", JOptionPane.ERROR_MESSAGE);
//        } else if (regex == 1 || regex == 2){
//            String data = sample1.getText();
//            if (simulateSample1.isSelected()){
//                data = sample1.getText();
//            } else if (simulateSample2.isSelected()) {
//                data = sample2.getText();
//            } else if (simulateSample3.isSelected()) {
//                data = sample3.getText();
//            } else if (simulateSample4.isSelected()) {
//                data = sample4.getText();
//            } else if (simulateSample5.isSelected()) {
//                data = sample5.getText();
//            }
//            canvas sim = new canvas(data, regex);
//            sim.setVisible(true);
//        }  
        String data = sample1.getText();
        
        if (simulateSample1.isSelected()){
            data = sample1.getText();
        } else if (simulateSample2.isSelected()) {
            data = sample2.getText();
        } else if (simulateSample3.isSelected()) {
            data = sample3.getText();
        } else if (simulateSample4.isSelected()) {
            data = sample4.getText();
        } else if (simulateSample5.isSelected()) {
            data = sample5.getText();
        }
        pickSimulation(data);
    }//GEN-LAST:event_simulate1ActionPerformed
    private void pickSimulation(String stringIn){
        if (regex == 1)
            sim.startReg1(stringIn);
        else if (regex == 2)
            sim.startReg2(stringIn);
        else
            JOptionPane.showMessageDialog(null, "No Regular Expression to Simulate!","Error", JOptionPane.ERROR_MESSAGE);
    }
    private void simulateSample5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateSample5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulateSample5ActionPerformed

    private void simulateSample4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateSample4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulateSample4ActionPerformed

    private void simulateSample3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateSample3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulateSample3ActionPerformed

    private void simulateSample2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateSample2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulateSample2ActionPerformed

    private void simulateSample1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateSample1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simulateSample1ActionPerformed

    private void compileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compileBtnActionPerformed
        // TODO add your handling code here:
        /*String sample = "";
        if(count <= 5){
            if(count == 1){
                sample = sample1.getText();
            } else if(count == 2){
                sample = sample2.getText();
            } else if(count == 3){
                sample = sample3.getText();
            } else if(count == 4){
                sample = sample4.getText();
            } else if(count == 5){
                sample = sample5.getText();
            }
            comp[count] = new compilerFunction(regex, sample);
            comp[count].question();
            comp[count].answer();
            if(count == 0){
                sample1Result.setText(comp[count].toString());
            } else if(count == 1){
                sample2Result.setText(comp[count].toString());
            } else if(count == 2){
                sample3Result.setText(comp[count].toString());
            } else if(count == 3){
                sample4Result.setText(comp[count].toString());
            } else if(count == 4){
                sample5Result.setText(comp[count].toString());
            }
            count++;
        }*/
        comp[0] = new compilerFunction(regex, sample1.getText());
        comp[0].question();
        comp[0].answer();
        sample1Result.setText(comp[0].toString());
        comp[1] = new compilerFunction(regex, sample2.getText());
        comp[1].question();
        comp[1].answer();
        sample2Result.setText(comp[1].toString());
        comp[2] = new compilerFunction(regex, sample3.getText());
        comp[2].question();
        comp[2].answer();
        sample3Result.setText(comp[2].toString());
        comp[3] = new compilerFunction(regex, sample4.getText());
        comp[3].question();
        comp[3].answer();
        sample4Result.setText(comp[3].toString());
        comp[4] = new compilerFunction(regex, sample5.getText());
        comp[4].question();
        comp[4].answer();
        sample5Result.setText(comp[4].toString());
        System.out.println(regex);
    }//GEN-LAST:event_compileBtnActionPerformed

    private void viewcfgpdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcfgpdaActionPerformed
        // TODO add your handling code here:
        if(regex == 0){
            JOptionPane.showMessageDialog(null, "No Regular Expression to Convert!","Error", JOptionPane.ERROR_MESSAGE);
        } else {
            cfgpda newWindow = new cfgpda(regex);
            newWindow.setVisible(true);
        }      
    }//GEN-LAST:event_viewcfgpdaActionPerformed

    private void sample1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sample1KeyTyped
        // TODO add your handling code here:
//        if(sample1.getText().length()==11) {  
//            evt.consume();
//        } 
    }//GEN-LAST:event_sample1KeyTyped

    private void sample2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sample2KeyTyped
        // TODO add your handling code here:
//        if(sample2.getText().length()==11) {  
//            evt.consume();
//        } 
    }//GEN-LAST:event_sample2KeyTyped

    private void sample3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sample3KeyTyped
        // TODO add your handling code here:
//        if(sample3.getText().length()==11) {  
//            evt.consume();
//        } 
    }//GEN-LAST:event_sample3KeyTyped

    private void sample4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sample4KeyTyped
        // TODO add your handling code here:
//        if(sample4.getText().length()==11) {  
//            evt.consume();
//        } 
    }//GEN-LAST:event_sample4KeyTyped

    private void sample5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sample5KeyTyped
        // TODO add your handling code here:
//        if(sample5.getText().length()==11) {  
//            evt.consume();
//        } 
    }//GEN-LAST:event_sample5KeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compileUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compileUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DFA;
    private javax.swing.JButton Regex1;
    private javax.swing.JButton Regex2;
    private javax.swing.JLabel StringValidation;
    private javax.swing.JButton compileBtn;
    private javax.swing.JLabel dfa1;
    private javax.swing.JLabel dfa2;
    private javax.swing.JPanel dfapanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel regEx;
    private javax.swing.JTextField sample1;
    private javax.swing.JLabel sample1Result;
    private javax.swing.JTextField sample2;
    private javax.swing.JLabel sample2Result;
    private javax.swing.JTextField sample3;
    private javax.swing.JLabel sample3Result;
    private javax.swing.JTextField sample4;
    private javax.swing.JLabel sample4Result;
    private javax.swing.JTextField sample5;
    private javax.swing.JLabel sample5Result;
    private javax.swing.JButton simulate1;
    private javax.swing.JRadioButton simulateSample1;
    private javax.swing.JRadioButton simulateSample2;
    private javax.swing.JRadioButton simulateSample3;
    private javax.swing.JRadioButton simulateSample4;
    private javax.swing.JRadioButton simulateSample5;
    private javax.swing.ButtonGroup simulateText;
    private javax.swing.JButton viewcfgpda;
    // End of variables declaration//GEN-END:variables
}
